<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Carbon\CarbonImmutable;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('t_document_contract')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'category_id' => 0,
                'template_id' => 1,
                'doc_type_id' => 1,
                'status_id' => 1,
                'cont_start_date' => null,
                'cont_end_date' => null,
                'conc_date' => null,
                'effective_date' => null,
                'cancel_date' => null,
                'expiry_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'title' => '契約書類テストタイトル',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_contract')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_contract')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'file_name' => '契約書テストファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);

        DB::table('t_document_deal')->insert([
            [
                'document_id' => 2,
                'company_id' => 1,
                'category_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 2,
                'status_id' => 1,
                'issue_date' => null,
                'expiry_date' => null,
                'payment_date' => null,
                'transaction_date' => null,
                'download_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'product_name' => 'テスト取引商品',
                'title' => 'テスト取引書類タイトル',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_transaction')->insert([
            [
                'document_id' => 2,
                'company_id' => 1,
                'user_id' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_transaction')->insert([
            [
                'document_id' => 2,
                'company_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 2,
                'file_name' => 'テスト取引ファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_document_internal')->insert([
            [
                'document_id' => 3,
                'company_id' => 2,
                'category_id' => 2,
                'template_id' => 1,
                'doc_type_id' => 3,
                'status_id' => 1,
                'doc_create_date' => null,
                'sign_finish_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'product_name' => 'テスト社内商品',
                'title' => 'テスト社内ドキュメント',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'content' => null,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_internal')->insert([
            [
                'document_id' => 3,
                'company_id' => 2,
                'user_id' => 3,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_internal')->insert([
            [
                'document_id' => 3,
                'company_id' => 2,
                'template_id' => 1,
                'doc_type_id' => 3,
                'file_name' => 'テスト社内ファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);

        DB::table('t_document_archive')->insert([
            [
                'document_id' => 4,
                'company_id' => 2,
                'category_id' => 3,
                'template_id' => 1,
                'doc_type_id' => 4,
                'scan_doc_flg' => 1,
                'status_id' => 1,
                'issue_date' => null,
                'expiry_date' => null,
                'transaction_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'title' => 'テスト取引ドキュメント',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'timestamp_user' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        
        DB::table('t_doc_permission_archive')->insert([
            [
                'document_id' => 4,
                'company_id' => 2,
                'user_id' => 4,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        
        DB::table('t_doc_storage_archive')->insert([
            [
                'document_id' => 4,
                'company_id' => 2,
                'template_id' => 1,
                'doc_type_id' => 4,
                'file_name' => 'テスト取引ファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
    }
}
