<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Carbon\CarbonImmutable;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('t_document_contract')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'category_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'status_id' => 1,
                'cont_start_date' => null,
                'cont_end_date' => null,
                'conc_date' => null,
                'effective_date' => null,
                'cancel_date' => null,
                'expiry_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'title' => 'テストドキュメント',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_document_deal')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'category_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'status_id' => 1,
                'issue_date' => null,
                'expiry_date' => null,
                'payment_date' => null,
                'transaction_date' => null,
                'download_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'product_name' => 'テスト商品',
                'title' => 'テストドキュメント',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_document_internal')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'category_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'status_id' => 1,
                'doc_create_date' => null,
                'sign_finish_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'product_name' => 'テスト商品',
                'title' => 'テストドキュメント',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'content' => null,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_document_archive')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'category_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'scan_doc_flg' => 1,
                'status_id' => 1,
                'issue_date' => null,
                'expiry_date' => null,
                'transaction_date' => null,
                'doc_no' => 1,
                'ref_doc_no' => null,
                'title' => 'テストドキュメント',
                'amount' => 999999,
                'currency_id' => 1,
                'counter_party_id' => 1,
                'remarks' => null,
                'doc_info' => null,
                'sign_level' => 1,
                'timestamp_user' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_contract')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_transaction')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_internal')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_permission_archive')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'user_id' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_contract')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'file_name' => 'テストファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_transaction')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'file_name' => 'テストファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_internal')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'file_name' => 'テストファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_doc_storage_archive')->insert([
            [
                'document_id' => 1,
                'company_id' => 1,
                'template_id' => 1,
                'doc_type_id' => 1,
                'file_name' => 'テストファイル',
                'file_size' => 1024,
                'file_path' => null,
                'file_hash' => null,
                'file_prot_flg' => 1,
                'file_prot_pw_flg' => 1,
                'file_timestamp_flg' => 1,
                'file_sign' => 1,
                'width' => 297,
                'height' => 210,
                'dpi' => null,
                'color_depth' => null,
                'pdf_type' => 'pdf',
                'pdf_version' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('t_document_workflow')->insert([
            [
                'company_id' => 1,
                'category_id' => 1,
                'document_id' => 1,
                'workflow_id' => 1,
                'app_user_id' => 1,
                'app_status' => 1,
                'app_date' => null,
                'wf_sort' => 1,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);            
        DB::table('t_log_doc_operation')->insert([
            [
                'log_id' => 1,
                'company_id' => 1,
                'category_id' => 1,
                'document_id' => 1,
                'operation_user_id' => 1,
                'before_content' => null,
                'after_contet' => null,
                'ip_address' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('m_user')->insert([
            [
                'user_id' => 1,
                'company_id' => 1,
                'user_type_id' => 1,
                'email' => 'test@test.jp',
                'family_name' => '大化',
                'first_name' => 'テスト',
                'full_name' => '大化　テスト',
                'family_name_kana' => 'タイカ',
                'first_name_kana' => 'テスト',
                'full_name_kana' => 'タイカ　テスト',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'JA',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('m_company_info')->insert([
            [
                'company_id' => 1,
                'company_name' => 'テスト会社',
                'company_name_kana' => 'テストガイシャ',
                'tax_id' => null,
                'effe_tax_start_date' => null,
                'effe_tax_end_date' => null,
                'country' => 'JA',
                'company_branch' => null,
                'zip_code' => '9999999',
                'address' => 'テスト住所',
                'tel' => '0123456789',
                'contract_start_date' => null,
                'contract_end_date' => null,
                'contract_service' => 'テスト',
                'contractor' => 'テスト',
                'invoice_department' => null,
                'invoice_attention' => null,
                'domain' => null,
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('m_company_counter_party')->insert([
            [
                'company_id' => 1,
                'counter_party_id' => 1,
                'counter_party_name' => 'テスト国',
                'counter_party_name_kana' => 'テストクニ',
                'counter_party_tax_id' => null,
                'counter_party_country' => 'JA',
                'counter_party_branch' => null,
                'counter_party_zip_code' => '9999999',
                'counter_party_address' => 'テスト住所',
                'counter_party_tel' => '0123456789',
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('m_company_department')->insert([
            [
                'company_id' => 1,
                'department_id' => 1,
                'department_name' => 1,
                'parent_id' => 1,
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        DB::table('m_user_role')->insert([
            [
                'company_id' => 1,
                'user_id' => 1,
                'admin_role' => true,
                'template_set_role' => true,
                'workflow_set_role' => true,
                'master_set_role' => true,
                'archive_func_role' => true,
                'ts_role' => true,
                'bulk_ts_role' => true,
                'bulk_veri_func_role' => true,
                'cont_doc_app_role' => true,
                'deal_doc_app_role' => true,
                'int_doc_app_role' => true,
                'arch_doc_app_role' => true,
                'use_cert_role' => true,
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],

       ]);
    }
}
