<?php

namespace Database\Seeders;

use Carbon\CarbonImmutable;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('m_company_info')->insert([
            [
                'company_id' => 1,
                'company_name' => 'テスト会社',
                'company_name_kana' => 'テストガイシャ',
                'tax_id' => null,
                'effe_tax_start_date' => null,
                'effe_tax_end_date' => null,
                'country' => 'JA',
                'company_branch' => null,
                'zip_code' => '9999999',
                'address' => 'テスト住所',
                'tel' => '0123456789',
                'contract_start_date' => null,
                'contract_end_date' => null,
                'contract_service' => 'テスト',
                'contractor' => 'テスト',
                'invoice_department' => null,
                'invoice_attention' => null,
                'domain' => null,
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_company_department')->insert([
            [
                'company_id' => 1,
                'department_id' => 1,
                'department_name' => 1,
                'parent_id' => 1,
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_user')->insert([
            [
                'company_id' => 1,
                'user_id' => 1,
                'user_type_id' => 0,
                'email' => 'test@test.jp',
                'family_name' => '大化',
                'first_name' => 'テスト',
                'full_name' => '大化　テスト',
                'family_name_kana' => 'タイカ',
                'first_name_kana' => 'テスト',
                'full_name_kana' => 'タイカ　テスト',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
       ]);
       \DB::table('m_user')->insert([
            [
                'company_id' => 1,
                'user_id' => 2,
                'user_type_id' => 0,
                'email' => 'testyamada@test.jp',
                'family_name' => '山田',
                'first_name' => 'タロウ',
                'full_name' => '山田　タロウ',
                'family_name_kana' => 'ヤマダ',
                'first_name_kana' => 'タロウ',
                'full_name_kana' => 'ヤマダ　タロウ',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_user')->insert([
            [
                'company_id' => 1,
                'user_id' => 3,
                'user_type_id' => 0,
                'email' => 'testsato@test.jp',
                'family_name' => '佐藤',
                'first_name' => '次郎',
                'full_name' => '佐藤　次郎',
                'family_name_kana' => 'サトウ',
                'first_name_kana' => 'ジロウ',
                'full_name_kana' => 'サトウ　ジロウ',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_user')->insert([
            [
                'company_id' => 2,
                'user_id' => 4,
                'user_type_id' => 0,
                'email' => 'testhanaki@test.jp',
                'family_name' => '花木',
                'first_name' => '一郎',
                'full_name' => '花木　一郎',
                'family_name_kana' => 'ハナキ',
                'first_name_kana' => 'イチロウ',
                'full_name_kana' => 'ハナキ　イチロウ',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_user')->insert([
            [
                'company_id' => 2,
                'user_id' => 5,
                'user_type_id' => 0,
                'email' => 'testkatou@test.jp',
                'family_name' => '加藤',
                'first_name' => '三郎',
                'full_name' => '加藤　三郎',
                'family_name_kana' => 'カトウ',
                'first_name_kana' => 'サブロウ',
                'full_name_kana' => 'カトウ　サブロウ',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_user')->insert([
            [
                'company_id' => 2,
                'user_id' => 6,
                'user_type_id' => 0,
                'email' => 'testkimura@test.jp',
                'family_name' => '木村',
                'first_name' => '史郎',
                'full_name' => '木村　史郎',
                'family_name_kana' => 'キムラ',
                'first_name_kana' => 'シロウ',
                'full_name_kana' => 'キムラ　シロウ',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
        \DB::table('m_user')->insert([
            [
                'company_id' => 1,
                'user_id' => 7,
                'user_type_id' => 0,
                'email' => 'host1@email.com',
                'family_name' => '木村',
                'first_name' => '史郎',
                'full_name' => '木村　史郎',
                'family_name_kana' => 'キムラ',
                'first_name_kana' => 'シロウ',
                'full_name_kana' => 'キムラ　シロウ',
                'tel' => '0123456789',
                'mobile_number' => '0123456789',
                'language' => 'ja',
                'profile_image' => null,
                'company_counter_party_id' => null,
                'group_array' => '[1]',
                'position' => '社員',
                'active_flg' => 1,
                'active_date' => null,
                'password' => Hash::make('taika'),
                'effe_start_date' => null,
                'effe_end_date' => null,
                'create_user' => 1,
                'create_datetime' => CarbonImmutable::now(),
                'update_user' => 1,
                'update_datetime' => CarbonImmutable::now(),
                'delete_user' => null,
                'delete_datetime' => null,
            ],
        ]);
    }
}
