# POST http://localhost/document/detail/?XDEBUG_SESSION_START=session_name HTTP/1.2
POST http://localhost/document/detail HTTP/1.2
x-kotsmp-authorization: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
Content-Type: application/json

{
    "document_id" : 1,
    "category_id" : 3,
    "company_id" : 1,
    "user_id" : 1,
    "user_type" : 1,
    "ip" : "192.168.x.x",
    "after_contet" : ""
}
