POST http://localhost/sample-login HTTP/1.2
x-kotsmp-authorization: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
Content-Type: application/json

{
    "mail_address": "sample@sample.com",
    "password" : "password"
}
